# Generated by Django 5.2.3 on 2025-06-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a photo of the sale item.', null=True, upload_to='sales/'),
        ),
        migrations.AlterField(
            model_name='storehours',
            name='closing_time',
            field=models.TimeField(help_text='Closing time (e.g. 09:30 PM)'),
        ),
        migrations.AlterField(
            model_name='storehours',
            name='day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], help_text='Day of the week.', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='storehours',
            name='is_special_day',
            field=models.BooleanField(default=False, help_text='Check if this is a special day (e.g. holiday)'),
        ),
        migrations.AlterField(
            model_name='storehours',
            name='opening_time',
            field=models.TimeField(help_text='Opening time (e.g. 07:00 AM)'),
        ),
        migrations.AlterField(
            model_name='storehours',
            name='special_note',
            field=models.CharField(blank=True, help_text="Special note for this day (e.g. 'Hours might differ')", max_length=100),
        ),
    ]
