# Generated by Django 5.2.3 on 2025-06-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_saleitem_image_alter_storehours_closing_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storehours',
            options={'ordering': ['date', 'day']},
        ),
        migrations.AddField(
            model_name='storehours',
            name='date',
            field=models.DateField(blank=True, help_text='Specific date for special/holiday hours (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='storehours',
            name='day',
            field=models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], help_text='Day of the week (leave blank for special/holiday hours)', max_length=10),
        ),
    ]
